Helpdesk/Routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

/**
 * 'admin' middleware and 'helpdesk' prefix applied to all routes (including names)
 *
 * @see \App\Providers\Route::register
 */

Route::admin('helpdesk', function () {
    // To be used in search/filter functionality (search-string.php)
    Route::get('statuses/index', 'Statuses@index')->name('statuses.index');

    // Tickets
    Route::post('tickets/{id}/update-partial', 'Tickets@updatePartial');
    Route::post('tickets/import', 'Tickets@import')->name('tickets.import');
    Route::get('tickets/export', 'Tickets@export')->name('tickets.export');
    Route::resource('tickets', 'Tickets')->middleware('dropzone');
    
    // Replies
    Route::post('replies/store', 'Replies@store');
    Route::patch('replies/{id}/update', 'Replies@update');
    Route::resource('replies', 'Replies');
});

Helpdesk/Http/Controllers/Api/Tickets.php
<?php

namespace Modules\Helpdesk\Http\Controllers\Api;

use App\Abstracts\Http\ApiController;
use Modules\Helpdesk\Http\Requests\Ticket as Request;
use Modules\Helpdesk\Http\Resources\Ticket as Resource;
use Modules\Helpdesk\Jobs\CreateTicket;
use Modules\Helpdesk\Jobs\DeleteTicket;
use Modules\Helpdesk\Jobs\UpdateTicket;
use Modules\Helpdesk\Models\Ticket;

class Tickets extends ApiController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function index()
    {
        $tickets = Ticket::with('category', 'replies')->collect();

        return Resource::collection($tickets);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function show($id)
    {
        $ticket = Ticket::with('category', 'replies')->find($id);

        return new Resource($ticket);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function store(Request $request)
    {
        $ticket = $this->dispatch(new CreateTicket($request));

        return $this->created(route('api.helpdesk.tickets.show', $ticket->id), new Resource($ticket));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  $ticket
     * @param  $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function update(Ticket $ticket, Request $request)
    {
        $ticket = $this->dispatch(new UpdateTicket($ticket, $request));

        return new Resource($ticket->fresh());
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $ticket = Ticket::with('replies')->find($id);

        if ($ticket !== null) {
            try {
                $this->dispatch(new DeleteTicket($ticket));
                return $this->noContent();
            } catch (\Exception $e) {
                $this->errorUnauthorized($e->getMessage());
            }
        } else {
            return $this->errorNotFound();
        }
    }
}

Helpdesk/Http/Controllers/Portal/Replies.php
<?php

namespace Modules\Helpdesk\Http\Controllers\Portal;

use App\Abstracts\Http\Controller;
use Illuminate\Http\Response;
use Modules\Helpdesk\Http\Requests\Reply as Request;
use Modules\Helpdesk\Jobs\CreateReply;

class Replies extends Controller
{
    /**
     * Store a newly created resource in storage.
     *
     * @param  Request $request
     *
     * @return Response
     */
    public function store(Request $request)
    {
        $response = $this->ajaxDispatch(new CreateReply($request));

        $response['redirect'] = route('portal.helpdesk.tickets.show', $request->get('ticket_id'));

        if ($response['success']) {
            $message = trans('messages.success.added', ['type' => trans_choice('helpdesk::general.replies', 1)]);

            flash($message)->success();
        } else {
            $message = $response['message'];

            flash($message)->error()->important();
        }

        return response()->json($response);
    }
}

Helpdesk/Http/Controllers/Portal/Statuses.php
<?php

namespace Modules\Helpdesk\Http\Controllers\Portal;

use App\Abstracts\Http\Controller;
use Illuminate\Http\Response;
use Modules\Helpdesk\Models\Status;

class Statuses extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $statuses = Status::collect();

        return $this->response('helpdesk::portal.statuses.index', compact('statuses'));
    }
}

Helpdesk/Http/Controllers/Portal/Tickets.php
<?php

namespace Modules\Helpdesk\Http\Controllers\Portal;

use App\Abstracts\Http\Controller;
use Illuminate\Http\Response;
use Modules\Helpdesk\Http\Requests\Ticket as Request;
use Modules\Helpdesk\Jobs\CreateTicket;
use Modules\Helpdesk\Models\Ticket;
use Modules\Helpdesk\Models\Status;
use Modules\Helpdesk\Models\Priority;
use App\Models\Setting\Category;
use App\Models\Document\Document;

class Tickets extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $tickets = Ticket::isOwner()
            ->with('category', 'status')
            ->collect(['created_at' => 'desc']);

        $t = $tickets->toArray();
        $first_status_id = Status::getFirstStatusID();
        $last_status_id = Status::getLastStatusID();

        return $this->response('helpdesk::portal.tickets.index', compact('tickets', 'first_status_id', 'last_status_id'));
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function categories()
    {
        $categories = Category::type('ticket')->get();

        return $this->response('helpdesk::portal.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $categories = Category::type('ticket')->orderBy('name')->take(setting('default.select_limit'))->pluck('name', 'id');

        $file_types = $this->getFileTypes();

        $statuses = Status::getAvailableStatuses(0)->pluck('name', 'id');
        $status_id = Status::getFirstStatusID();

        $priorities = Priority::collect()->pluck('name', 'id');
        $priority_id = Priority::getDefaultPriorityID();

        $documents = Document::where('contact_id', user()->contact->id)->pluck('document_number', 'id');

        return view('helpdesk::portal.tickets.create', compact(
            'categories',
            'file_types',
            'statuses',
            'status_id',
            'priorities',
            'priority_id',
            'documents'
        ));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function store(Request $request)
    {
        $response = $this->ajaxDispatch(new CreateTicket($request));

        if ($response['success']) {
            $response['redirect'] = route('portal.helpdesk.tickets.index');

            $message = trans('messages.success.added', ['type' => trans_choice('helpdesk::general.tickets', 1)]);

            flash($message)->success();
        } else {
            $response['redirect'] = route('portal.helpdesk.tickets.create');

            $message = $response['message'];

            flash($message)->error()->important();
        }

        return response()->json($response);
    }

    /**
     * Show the form for viewing the specified resource.
     *
     * @return Response
     */
    public function show(Ticket $ticket)
    {
        if (! user()->owns($ticket)) {
            // In case the URL is directly accessed
            abort(403);
        }

        $ticket->load('category', 'status');

        $limit = (int) request('limit', setting('default.list_limit', '25'));
        $replies = $this->paginate($ticket->replies->where('internal', false)->sortByDesc('created_at'), $limit);

        $file_types = $this->getFileTypes();

        $first_status_id = Status::getFirstStatusID();
        $last_status_id = Status::getLastStatusID();

        return view('helpdesk::portal.tickets.show', compact('ticket',
            'replies',
            'file_types',
            'first_status_id',
            'last_status_id'
        ));
    }

    /**
     * Get supported file types helper
     */
    private function getFileTypes()
    {
        $file_types = [];

        $file_type_mimes = explode(',', config('filesystems.mimes'));

        foreach ($file_type_mimes as $mime) {
            $file_types[] = '.' . $mime;
        }

        return implode(',', $file_types);
    }
}

Helpdesk/Http/Controllers/Tickets.php
<?php

namespace Modules\Helpdesk\Http\Controllers;

use App\Abstracts\Http\Controller;
use Illuminate\Http\Response;
use Illuminate\Http\Request as BasicRequest;
use Modules\Helpdesk\Http\Requests\Ticket as Request;
use Modules\Helpdesk\Jobs\CreateTicket;
use Modules\Helpdesk\Jobs\UpdateTicket;
use Modules\Helpdesk\Jobs\DeleteTicket;
use Modules\Helpdesk\Models\Ticket;
use Modules\Helpdesk\Models\Status;
use Modules\Helpdesk\Models\Priority;
use App\Models\Setting\Category;
use App\Models\Document\Document;
use App\Http\Requests\Common\Import as ImportRequest;
use Modules\Helpdesk\Imports\Tickets as Import;
use Modules\Helpdesk\Exports\Tickets as Export;

class Tickets extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $tickets = Ticket::with('category', 'owner', 'assignee', 'status', 'priority')->collect(['created_at' => 'desc']);

        $first_status_id = Status::getFirstStatusID();
        $last_status_id = Status::getLastStatusID();

        return $this->response('helpdesk::tickets.index', compact('tickets', 'first_status_id', 'last_status_id'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $categories = Category::type('ticket')->orderBy('name')->take(setting('default.select_limit'))->pluck('name', 'id');

        $file_types = $this->getFileTypes();

        $statuses = Status::getAvailableStatuses(0)->pluck('name', 'id');
        $status_id = Status::getFirstStatusID();

        $priorities = Priority::collect()->pluck('name', 'id');
        $priority_id = Priority::getDefaultPriorityID();

        $assignees = company()->users()->collect()->filter(function ($user) {
            return $user->can('update-helpdesk-tickets');
        })->pluck('name', 'id');

        $documents = Document::all()->pluck('document_number', 'id');

        return view('helpdesk::tickets.create', compact(
            'categories',
            'file_types',
            'statuses',
            'status_id',
            'priorities',
            'priority_id',
            'assignees',
            'documents'
        ));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function store(Request $request)
    {
        $response = $this->ajaxDispatch(new CreateTicket($request));

        if ($response['success']) {
            $response['redirect'] = route('helpdesk.tickets.index');

            $message = trans('messages.success.added', ['type' => trans_choice('helpdesk::general.tickets', 1)]);

            flash($message)->success();
        } else {
            $response['redirect'] = route('helpdesk.tickets.create');

            $message = $response['message'];

            flash($message)->error()->important();
        }

        return response()->json($response);
    }

    /**
     * Show the specified resource.
     *
     * @param $ticket
     *
     * @return Response
     */
    public function show(Ticket $ticket)
    {
        $ticket->load('category', 'status', 'priority');

        $limit = (int) request('limit', setting('default.list_limit', '25'));
        $replies = $this->paginate($ticket->replies->sortByDesc('created_at'), $limit);

        $statuses = Status::getAvailableStatuses($ticket->status_id)->pluck('name', 'id');
        $first_status_id = Status::getFirstStatusID();
        $last_status_id = Status::getLastStatusID();

        $priorities = Priority::collect()->pluck('name', 'id');

        $assignees = company()->users()->collect()->filter(function ($user) {
            return $user->can('update-helpdesk-tickets');
        })->pluck('name', 'id');

        return view('helpdesk::tickets.show', compact(
            'ticket',
            'replies',
            'statuses',
            'first_status_id',
            'last_status_id',
            'priorities',
            'assignees'
        ));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param $ticket
     *
     * @return Response
     */
    public function edit(Ticket $ticket)
    {
        $categories = Category::type('ticket')->orderBy('name')->take(setting('default.select_limit'))->pluck('name', 'id');

        $file_types = $this->getFileTypes();

        $statuses = Status::getAvailableStatuses($ticket->status_id)->pluck('name', 'id');
        $disabled = ($ticket->status_id == Status::getLastStatusID());

        $priorities = Priority::collect()->pluck('name', 'id');

        $assignees = company()->users()->collect()->filter(function ($user) {
            return $user->can('update-helpdesk-tickets');
        })->pluck('name', 'id');

        $documents = Document::all()->pluck('document_number', 'id');

        return view('helpdesk::tickets.edit', compact(
            'ticket',
            'categories',
            'file_types',
            'statuses',
            'disabled',
            'priorities',
            'assignees',
            'documents'
        ));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Ticket $ticket
     * @param  Request $request
     *
     * @return Response
     */
    public function update(Ticket $ticket, Request $request)
    {
        $response = $this->ajaxDispatch(new UpdateTicket($ticket, $request));

        if ($response['success']) {
            $response['redirect'] = route('helpdesk.tickets.show', $ticket->id);

            $message = trans('messages.success.updated', ['type' => $ticket->name]);

            flash($message)->success();
        } else {
            $response['redirect'] = route('helpdesk.tickets.edit', $ticket->id);

            $message = $response['message'];

            flash($message)->error()->important();
        }

        return response()->json($response);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  USRequest $request
     *
     * @return Response
     */
    public function updatePartial(int $ticket_id, BasicRequest $request)
    {
        $ticket = Ticket::where('id', $ticket_id)->first();

        $response = $this->ajaxDispatch(new UpdateTicket($ticket, $request));

        $response['redirect'] = route('helpdesk.tickets.show', $ticket->id);

        if ($response['success']) {
            $message = trans('messages.success.updated', ['type' => $ticket->name]);

            flash($message)->success();
        } else {
            $message = $response['message'];

            flash($message)->error()->important();
        }

        return response()->json($response);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param $ticket
     *
     * @return Response
     */
    public function destroy(Ticket $ticket)
    {
        $response = $this->ajaxDispatch(new DeleteTicket($ticket));

        $response['redirect'] = route('helpdesk.tickets.index');

        if ($response['success']) {
            $message = trans('messages.success.deleted', ['type' => $ticket->name]);

            flash($message)->success();
        } else {
            $message = $response['message'];

            flash($message)->error()->important();
        }

        return response()->json($response);
    }

    /**
     * Import the specified resource.
     *
     * @param  ImportRequest  $request
     *
     * @return Response
     */
    public function import(ImportRequest $request)
    {
        $response = $this->importExcel(new Import, $request, trans_choice('helpdesk::general.tickets', 2));

        if ($response['success']) {
            $response['redirect'] = route('helpdesk.tickets.index');

            flash($response['message'])->success();
        } else {
            $response['redirect'] = route('import.create', ['helpdesk', 'tickets']);

            flash($response['message'])->error()->important();
        }

        return response()->json($response);
    }

    /**
     * Export the specified resource.
     *
     * @return Response
     */
    public function export()
    {
        return $this->exportExcel(new Export, trans_choice('helpdesk::general.tickets', 2));
    }

    /**
     * Get supported file types helper
     */
    private function getFileTypes()
    {
        $file_types = [];

        $file_type_mimes = explode(',', config('filesystems.mimes'));

        foreach ($file_type_mimes as $mime) {
            $file_types[] = '.' . $mime;
        }

        return implode(',', $file_types);
    }
}

Helpdesk/Resources/views/portal/tickets/create.blade.php
<x-layouts.admin>
    <x-slot name="title">{{ trans('general.title.new', ['type' => trans_choice('helpdesk::general.tickets', 1)]) }}
    </x-slot>

    <x-slot name="content">
        <x-form.container>
            <x-form id="ticket" route="portal.helpdesk.tickets.store">
                <x-form.section>
                    <x-slot name="head">
                        <x-form.section.head title="{{ trans('general.general') }}"
                            description="{{ trans('helpdesk::general.form_description.create') }}" />
                    </x-slot>

                    <x-slot name="body">
                        <x-form.group.text name="subject" label="{{ trans('helpdesk::general.ticket.subject') }}" />

                        <x-form.group.category type="ticket" without-add-new />

                        <x-form.group.select multiple name="document_ids"
                            label="{{ trans('helpdesk::general.ticket.related_to') }}" :options="$documents"
                            not-required form-group-class="sm:col-span-3 el-select-tags-pl-38" />

                        <x-form.group.select name="status_id"
                            label="{{ trans_choice('helpdesk::general.statuses', 1) }}" :options="$statuses"
                            :selected="$status_id" form-group-class="sm:col-span-3 el-select-tags-pl-38"
                            :readonly="true" />

                        <x-form.group.textarea name="message"
                            label="{{ trans('helpdesk::general.ticket.message') }}" />

                        <x-form.group.attachment />

                        <x-form.input.hidden name="name" />
                    </x-slot>
                </x-form.section>

                <x-form.section>
                    <x-slot name="foot">
                        <x-form.buttons cancel-route="portal.helpdesk.tickets.index" />
                    </x-slot>
                </x-form.section>
            </x-form>
        </x-form.container>
    </x-slot>

    <x-script alias="helpdesk" file="tickets" />
</x-layouts.admin>

Helpdesk/Resources/views/portal/tickets/show.blade.php
<x-layouts.admin>
    <x-slot name="title">
        {{ trans_choice('helpdesk::general.tickets', 1) . ' ' . $ticket->name }}
    </x-slot>

    <x-slot name="buttons">
        @can('create-helpdesk-portal-tickets')
            <x-link href="{{ route('portal.helpdesk.tickets.create') }}" kind="primary">
                {{ trans('general.title.new', ['type' => trans_choice('helpdesk::general.tickets', 1)]) }}
            </x-link>
        @endcan

        @can('update-helpdesk-portal-tickets')
            <x-link href="{{ route('portal.helpdesk.tickets.edit', $ticket->id) }}">
                {{ trans('general.edit') }}
            </x-link>
        @endcan
    </x-slot>

    <x-slot name="content">
        <x-show.container>
            <x-show.summary>
                <div class="flex flex-col text-base mb-5">
                    <span class="text-xl mb-5">{{ $ticket->subject }}</span>
                    <div class="font-medium">{{ trans('helpdesk::general.ticket.message') }}</div>
                    <span class="mb-5">{!! nl2br($ticket->message) !!}</span>

                    @if ($ticket->attachment)
                        <div class="justify-start pb-4" x-data="{ attachment: null }">
                            <div class="relative w-full text-left cursor-pointer group"
                                x-on:click="attachment !== 1 ? attachment = 1 : attachment = null">
                                <span
                                    class="font-medium border-b border-transparent transition-all group-hover:border-black">
                                    {{ trans_choice('general.attachments', 2) }}
                                </span>

                                <div class="text-black-400 text-sm">{{ trans('helpdesk::general.download') }}</div>

                                <span class="material-icons absolute right-0 top-0 transition-all transform"
                                    x-bind:class="attachment === 1 ? 'rotate-180' : ''">expand_more</span>
                            </div>

                            <div class="relative overflow-hidden transition-all max-h-0 duration-700" style=""
                                x-ref="container1"
                                x-bind:style="attachment == 1 ? 'max-height: ' + $refs.container1.scrollHeight + 'px' : ''">
                                @foreach ($ticket->attachment as $file)
                                    <x-media.file :file="$file" />
                                @endforeach
                            </div>
                        </div>
                    @endif
                </div>
            </x-show.summary>

            <x-show.content>
                <x-show.content.left>
                    <div class="flex flex-col text-sm mb-5">
                        <div class="font-medium">{{ trans('helpdesk::general.ticket.created') }}</div>
                        <x-date date="{{ $ticket->created_at }}" />{{ $ticket->created_at->format('H:i') }}
                    </div>

                    <div class="flex flex-col text-sm mb-5">
                        <div class="font-medium">{{ trans('helpdesk::general.ticket.updated') }}</div>
                        <x-date date="{{ $ticket->updated_at }}" />{{ $ticket->updated_at->format('H:i') }}
                    </div>

                    <div class="flex flex-col text-sm mb-5">
                        <div class="font-medium">{{ trans('helpdesk::general.ticket.reporter') }}</div>
                        <span>{{ $ticket->owner->name }}</span>
                    </div>

                    <div class="flex flex-col text-sm mb-5">
                        <div class="font-medium">{{ trans('helpdesk::general.ticket.assignee') }}</div>
                        <span>{{ $ticket->assignee->name }}</span>
                    </div>

                    <div class="flex flex-col text-sm mb-5">
                        <div class="font-medium">{{ trans_choice('general.categories', 1) }}</div>
                        <span>{{ $ticket->category->name }}</span>
                    </div>

                    <div class="flex flex-col text-sm mb-5">
                        <div class="font-medium">{{ trans_choice('helpdesk::general.statuses', 1) }}</div>
                        <span>{{ $ticket->status->name }}</span>
                    </div>

                    <div class="flex flex-col text-sm mb-5">
                        <div class="font-medium">{{ trans_choice('helpdesk::general.priorities', 1) }}</div>
                        <span>{{ $ticket->priority->name }}</span>
                    </div>

                    <div class="flex flex-col text-sm mb-5">
                        @if (count($ticket->documents))
                            <div class="font-medium">{{ trans('helpdesk::general.ticket.related_to') }}</div>
                            <span>
                                @foreach ($ticket->documents as $document)
                                    <a class="border-black border-b border-dashed"
                                        href="{{ route($document->document->type == 'invoice' ? 'invoices.show' : 'bills.show', $document->document->id) }}">
                                        {{ $document->document->document_number }}
                                    </a><br>
                                @endforeach
                            </span>
                        @else
                            <div class="font-medium">{{ trans('helpdesk::general.ticket.not_related') }}</div>
                        @endif
                    </div>
                </x-show.content.left>

                <x-show.content.right>
                    <div class="w-12/12">
                        <div class="flex">
                            <h3 class="flex-1 text-left">{{ trans_choice('helpdesk::general.replies', 2) }}</h3>
                            <x-link href="javascript:;" kind="secondary" data-portal_flag="true"
                                @click="onReplyCreateModalOpen({{ $ticket->id }}, $event)">
                                {{ trans('helpdesk::general.reply.new_reply') }}
                            </x-link>
                        </div>

                        <x-table>
                            <x-table.thead>
                                <x-table.tr class="flex items-center px-1">
                                    <x-table.th class="w-3/12">
                                        <x-slot name="first">
                                            <x-sortablelink column="user"
                                                title="{{ trans_choice('general.users', 1) }}" :arguments="['class' => 'col-aka', 'rel' => 'nofollow']" />
                                        </x-slot>
                                        <x-slot name="second">
                                            <x-sortablelink column="created_at"
                                                title="{{ trans('general.created') }}" />
                                        </x-slot>
                                    </x-table.th>

                                    <x-table.th class="w-1/12"></x-table.th>

                                    <x-table.th class="w-8/12">
                                        <x-sortablelink column="description"
                                            title="{{ trans('helpdesk::general.ticket.message') }}" />
                                    </x-table.th>
                                </x-table.tr>
                            </x-table.thead>

                            <x-table.tbody>
                                @foreach ($replies as $reply)
                                    <x-table.tr href="{{ route('portal.helpdesk.replies.edit', $reply->id) }}"
                                        data-table-list
                                        class="relative flex items-center border-b hover:bg-gray-100 px-1 group">
                                        <x-table.td class="w-3/12 truncate">
                                            <x-slot name="first">
                                                {{ $reply->owner->name }}
                                            </x-slot>
                                            <x-slot name="second">
                                                <x-date date="{{ $reply->created_at }}" />
                                            </x-slot>
                                        </x-table.td>

                                        <x-table.td class="w-1/12 truncate"></x-table.td>

                                        <x-table.td class="w-8/12">
                                            <div class="whitespace-normal">
                                                {{ $reply->message }}
                                            </div>
                                        </x-table.td>

                                        @can(['update-helpdesk-replies', 'delete-helpdesk-replies'])
                                            <x-table.td kind="action" class="p-0" override="class">
                                                <x-table.actions :model="$reply" />
                                            </x-table.td>
                                        @endcan

                                    </x-table.tr>
                                @endforeach
                            </x-table.tbody>
                        </x-table>

                        <x-pagination :items="$replies" />
                    </div>
                </x-show.content.right>
            </x-show.content>
        </x-show.container>

        @push('content_content_end')
            <akaunting-modal :show="create_reply.modal" @cancel="create_reply.modal = false"
                :title="'{{ trans('helpdesk::general.reply.new_reply') }}'" :message="create_reply.html"
                :button_cancel="'{{ trans('general.button.save') }}'"
                :button_delete="'{{ trans('general.button.cancel') }}'">
                <template #modal-body>
                    @include('helpdesk::modals.replies.create')
                </template>

                <template #card-footer>
                    <div class="flex items-center justify-end">
                        <button type="button" class="px-6 py-1.5 hover:bg-gray-200 rounded-lg ltr:mr-2 rtl:ml-2"
                            @click="closeReplyCreateModal">
                            {{ trans('general.cancel') }}
                        </button>

                        <button :disabled="create_reply_form.loading" type="button"
                            class="relative flex items-center justify-center bg-green hover:bg-green-700 text-white px-6 py-1.5 text-base rounded-lg disabled:bg-green-100"
                            @click="onReplyCreate">
                            <i v-if="create_reply_form.loading"
                                class="animate-submit delay-[0.28s] absolute w-2 h-2 rounded-full left-0 right-0 -top-3.5 m-auto before:absolute before:w-2 before:h-2 before:rounded-full before:animate-submit before:delay-[0.14s] after:absolute after:w-2 after:h-2 after:rounded-full after:animate-submit before:-left-3.5 after:-right-3.5 after:delay-[0.42s]"></i>
                            <span
                                :class="[{ 'opacity-0': create_reply_form.loading }]">{{ trans('general.confirm') }}</span>
                        </button>
                    </div>
                </template>
            </akaunting-modal>
        @endpush

    </x-slot>

    <x-script alias="helpdesk" file="tickets" />
</x-layouts.admin>